org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true
# Disabling Jetifier as most modern libraries are already AndroidX.
android.enableJetifier=false
android.nonTransitiveRClass=true

# Fix for Kotlin compile daemon connection issues
kotlin.daemon.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g

# Use in-process strategy to avoid connection issues between Gradle and the Kotlin daemon
kotlin.compiler.execution.strategy=in-process

